// ============================================================
// LOTE 2 — Fisioterapia (agregar dentro de ITEMS_DETALLE,
// después de las escalas ya agregadas, antes del cierre "};")
// ============================================================

'rmi':{
secciones:[
{n:'Rivermead Mobility Index — cada ítem: 0=No puede, 1=Sí puede',items:[
{t:'Voltearse en la cama de un lado a otro',ops:[0,1]},
{t:'Pasar de tumbado a sentado en el borde de la cama',ops:[0,1]},
{t:'Mantener el equilibrio sentado sin apoyo (10 segundos)',ops:[0,1]},
{t:'Pasar de sentado a de pie (en menos de 15 segundos, con o sin ayuda)',ops:[0,1]},
{t:'Permanecer de pie sin apoyo (10 segundos)',ops:[0,1]},
{t:'Realizar una transferencia (cama a silla y viceversa)',ops:[0,1]},
{t:'Caminar dentro de casa con ayuda si es necesario',ops:[0,1]},
{t:'Subir y bajar un tramo de escaleras',ops:[0,1]},
{t:'Caminar en exteriores sobre terreno llano',ops:[0,1]},
{t:'Caminar en exteriores sobre terreno irregular',ops:[0,1]},
{t:'Bañarse de forma independiente (entrar, lavarse, salir)',ops:[0,1]},
{t:'Subir y bajar 4 escalones sin usar el pasamanos',ops:[0,1]},
{t:'Correr 10 metros en 4 segundos (o recoger un objeto del suelo)',ops:[0,1]},
{t:'Caminar más de 400 metros sin descansar',ops:[0,1]},
{t:'Usar transporte público de forma independiente',ops:[0,1]},
]},
],
interp:(p)=>p>=12?{t:'Movilidad funcional alta.',bg:'#E8F5F0',c:'#1A7A5E'}:p>=7?{t:'Movilidad funcional moderada.',bg:'#FFF3EB',c:'#C05621'}:{t:'Movilidad funcional muy limitada. Requiere apoyo constante.',bg:'#FFF5F5',c:'#C53030'},
},

'rmdq':{
secciones:[
{n:'Marque las afirmaciones que describen su situación HOY debido al dolor de espalda (0=No aplica, 1=Aplica)',items:[
{t:'Me quedo en casa la mayor parte del tiempo por mi espalda',ops:[0,1]},
{t:'Cambio de posición con frecuencia para poner mi espalda cómoda',ops:[0,1]},
{t:'Camino más despacio de lo habitual por mi espalda',ops:[0,1]},
{t:'Por mi espalda no hago ninguna de las tareas que suelo hacer en casa',ops:[0,1]},
{t:'Por mi espalda uso el pasamanos para subir escaleras',ops:[0,1]},
{t:'Por mi espalda me acuesto a descansar con más frecuencia',ops:[0,1]},
{t:'Por mi espalda tengo que sujetarme a algo para levantarme de un sillón',ops:[0,1]},
{t:'Por mi espalda trato de conseguir que otras personas hagan las cosas por mí',ops:[0,1]},
{t:'Me visto más despacio de lo normal por mi espalda',ops:[0,1]},
{t:'Solo permanezco de pie durante cortos periodos de tiempo por mi espalda',ops:[0,1]},
{t:'Por mi espalda trato de no agacharme ni arrodillarme',ops:[0,1]},
{t:'Me cuesta levantarme de una silla por mi espalda',ops:[0,1]},
{t:'Me duele la espalda casi todo el tiempo',ops:[0,1]},
{t:'Me cuesta darme la vuelta en la cama por mi espalda',ops:[0,1]},
{t:'Mi apetito no es muy bueno por el dolor de espalda',ops:[0,1]},
{t:'Tengo problemas para ponerme calcetines o medias por el dolor',ops:[0,1]},
{t:'Solo camino distancias cortas por mi espalda',ops:[0,1]},
{t:'Duermo peor por mi espalda',ops:[0,1]},
{t:'Por mi espalda me visto con ayuda de otra persona',ops:[0,1]},
{t:'Permanezco sentado la mayor parte del día por mi espalda',ops:[0,1]},
{t:'Evito hacer trabajos pesados en casa por mi espalda',ops:[0,1]},
{t:'Por mi dolor de espalda estoy más irritable e impaciente con la gente',ops:[0,1]},
{t:'Subo escaleras más despacio de lo habitual por mi espalda',ops:[0,1]},
{t:'Me quedo casi todo el tiempo en cama por mi espalda',ops:[0,1]},
]},
],
interp:(p)=>p<=4?{t:'Discapacidad mínima por dolor lumbar.',bg:'#E8F5F0',c:'#1A7A5E'}:p<=12?{t:'Discapacidad moderada.',bg:'#FFF3EB',c:'#C05621'}:{t:'Discapacidad severa por dolor lumbar. Requiere intervención activa.',bg:'#FFF5F5',c:'#C53030'},
},

'womac':{
secciones:[
{n:'Dolor (0=Ninguno, 1=Leve, 2=Moderado, 3=Severo, 4=Extremo) — al caminar, subir/bajar escaleras, en la noche, sentado/acostado, de pie',items:[
{t:'Dolor al caminar sobre superficie plana',ops:[0,1,2,3,4]},
{t:'Dolor al subir o bajar escaleras',ops:[0,1,2,3,4]},
{t:'Dolor nocturno en la cama',ops:[0,1,2,3,4]},
{t:'Dolor al estar sentado o acostado',ops:[0,1,2,3,4]},
{t:'Dolor al estar de pie',ops:[0,1,2,3,4]},
]},
{n:'Rigidez (0=Ninguna, 1=Leve, 2=Moderada, 3=Severa, 4=Extrema)',items:[
{t:'Rigidez matutina al despertar',ops:[0,1,2,3,4]},
{t:'Rigidez posterior a estar sentado, acostado o en reposo durante el día',ops:[0,1,2,3,4]},
]},
{n:'Función física (0=Ninguna dificultad, 1=Leve, 2=Moderada, 3=Severa, 4=Extrema)',items:[
{t:'Bajar escaleras',ops:[0,1,2,3,4]},
{t:'Subir escaleras',ops:[0,1,2,3,4]},
{t:'Levantarse estando sentado',ops:[0,1,2,3,4]},
{t:'Estar de pie',ops:[0,1,2,3,4]},
{t:'Agacharse hacia el suelo',ops:[0,1,2,3,4]},
{t:'Caminar sobre superficie plana',ops:[0,1,2,3,4]},
{t:'Entrar o salir de un carro',ops:[0,1,2,3,4]},
{t:'Ir de compras',ops:[0,1,2,3,4]},
{t:'Ponerse medias o calcetines',ops:[0,1,2,3,4]},
{t:'Levantarse de la cama',ops:[0,1,2,3,4]},
{t:'Quitarse medias o calcetines',ops:[0,1,2,3,4]},
{t:'Estar acostado en la cama',ops:[0,1,2,3,4]},
{t:'Entrar o salir de la ducha/bañera',ops:[0,1,2,3,4]},
{t:'Estar sentado',ops:[0,1,2,3,4]},
{t:'Sentarse o levantarse del inodoro',ops:[0,1,2,3,4]},
{t:'Tareas domésticas pesadas',ops:[0,1,2,3,4]},
{t:'Tareas domésticas ligeras',ops:[0,1,2,3,4]},
]},
],
interp:(p)=>p<=20?{t:'Afectación funcional leve.',bg:'#E8F5F0',c:'#1A7A5E'}:p<=50?{t:'Afectación funcional moderada.',bg:'#FFF3EB',c:'#C05621'}:{t:'Afectación funcional severa. Impacto importante en rodilla/cadera.',bg:'#FFF5F5',c:'#C53030'},
},

'odi':{
secciones:[
{n:'Cada sección se puntúa de 0 (mejor) a 10 (peor), representando el % de discapacidad en esa área',items:[
{t:'Intensidad del dolor',ops:[0,2,4,6,8,10]},
{t:'Cuidado personal (lavarse, vestirse)',ops:[0,2,4,6,8,10]},
{t:'Levantar objetos',ops:[0,2,4,6,8,10]},
{t:'Caminar',ops:[0,2,4,6,8,10]},
{t:'Estar sentado',ops:[0,2,4,6,8,10]},
{t:'Estar de pie',ops:[0,2,4,6,8,10]},
{t:'Dormir',ops:[0,2,4,6,8,10]},
{t:'Vida sexual (si aplica)',ops:[0,2,4,6,8,10]},
{t:'Vida social',ops:[0,2,4,6,8,10]},
{t:'Viajar',ops:[0,2,4,6,8,10]},
]},
],
interp:(p)=>p<=20?{t:'Discapacidad mínima.',bg:'#E8F5F0',c:'#1A7A5E'}:p<=40?{t:'Discapacidad moderada.',bg:'#FFF3EB',c:'#C05621'}:p<=60?{t:'Discapacidad severa.',bg:'#FFF5F5',c:'#C53030'}:p<=80?{t:'Discapacidad muy severa. Limita casi todas las actividades.',bg:'#FFF5F5',c:'#C53030'}:{t:'Postración. Paciente encamado o con síntomas exagerados. Revisar validez.',bg:'#FFF5F5',c:'#C53030'},
},

'constant-murley':{
secciones:[
{n:'Dolor (máx 15 pts)',items:[
{t:'Nivel de dolor en el hombro (0=Severo ... 15=Sin dolor)',ops:[0,5,10,15]},
]},
{n:'Actividades de la vida diaria (máx 20 pts)',items:[
{t:'Nivel de actividad laboral posible (0-4)',ops:[0,1,2,3,4]},
{t:'Nivel de actividad recreativa/deportiva posible (0-4)',ops:[0,1,2,3,4]},
{t:'Afectación del sueño por el hombro (0-2)',ops:[0,1,2]},
{t:'Posición más alta alcanzada sin dolor con la mano (0-10: cintura, xifoides, cuello, cabeza, sobre la cabeza)',ops:[0,2,4,6,8,10]},
]},
{n:'Rango de movimiento (máx 40 pts)',items:[
{t:'Flexión anterior (0-10)',ops:[0,2,4,6,8,10]},
{t:'Abducción (0-10)',ops:[0,2,4,6,8,10]},
{t:'Rotación externa (0-10)',ops:[0,2,4,6,8,10]},
{t:'Rotación interna (0-10)',ops:[0,2,4,6,8,10]},
]},
{n:'Fuerza muscular (máx 25 pts)',items:[
{t:'Fuerza en abducción del hombro (0=Sin fuerza ... 25=Fuerza máxima)',ops:[0,5,10,15,20,25]},
]},
],
interp:(p)=>p>=80?{t:'Función de hombro excelente.',bg:'#E8F5F0',c:'#1A7A5E'}:p>=60?{t:'Función de hombro buena, afectación leve.',bg:'#E8F5F0',c:'#1A7A5E'}:p>=40?{t:'Función de hombro moderadamente afectada.',bg:'#FFF3EB',c:'#C05621'}:{t:'Función de hombro severamente afectada.',bg:'#FFF5F5',c:'#C53030'},
},

'mas':{
secciones:[
{n:'Motor Assessment Scale — 8 ítems funcionales, cada uno 0-6 (0=No realiza, 6=Desempeño óptimo)',items:[
{t:'De supino a decúbito lateral (hacia el lado afectado)',ops:[0,1,2,3,4,5,6]},
{t:'De supino a sentado al borde de la cama',ops:[0,1,2,3,4,5,6]},
{t:'Equilibrio en sedestación',ops:[0,1,2,3,4,5,6]},
{t:'De sentado a de pie',ops:[0,1,2,3,4,5,6]},
{t:'Marcha',ops:[0,1,2,3,4,5,6]},
{t:'Función del brazo (alcance y manipulación)',ops:[0,1,2,3,4,5,6]},
{t:'Movimiento de la mano',ops:[0,1,2,3,4,5,6]},
{t:'Actividades avanzadas de la mano',ops:[0,1,2,3,4,5,6]},
]},
],
interp:(p)=>p>=40?{t:'Función motora global buena.',bg:'#E8F5F0',c:'#1A7A5E'}:p>=24?{t:'Función motora global moderada.',bg:'#FFF3EB',c:'#C05621'}:{t:'Función motora global severamente comprometida.',bg:'#FFF5F5',c:'#C53030'},
},

'rivermead':{
secciones:[
{n:'Función gruesa (13 ítems, 0=No puede, 1=Sí puede)',items:[
{t:'Sentarse sin apoyo',ops:[0,1]},
{t:'Ponerse de pie desde sentado',ops:[0,1]},
{t:'Pararse sin apoyo',ops:[0,1]},
{t:'Transferencia de silla a cama',ops:[0,1]},
{t:'Caminar con ayuda',ops:[0,1]},
{t:'Subir un escalón',ops:[0,1]},
{t:'Caminar sin ayuda',ops:[0,1]},
{t:'Caminar sobre terreno irregular',ops:[0,1]},
{t:'Subir y bajar 4 escalones',ops:[0,1]},
{t:'Correr o caminar rápido',ops:[0,1]},
{t:'Saltar en el sitio',ops:[0,1]},
{t:'Saltar sobre el lado afectado',ops:[0,1]},
{t:'Caminar y girar rápidamente',ops:[0,1]},
]},
{n:'Pierna y tronco (10 ítems, 0=No puede, 1=Sí puede)',items:[
{t:'Flexión de cadera en supino',ops:[0,1]},
{t:'Extensión de cadera en prono',ops:[0,1]},
{t:'Flexión de rodilla en sedestación',ops:[0,1]},
{t:'Dorsiflexión de tobillo en sedestación',ops:[0,1]},
{t:'Puente pélvico (elevar cadera en supino)',ops:[0,1]},
{t:'Rotación de tronco en sedestación',ops:[0,1]},
{t:'Control de tronco en bipedestación',ops:[0,1]},
{t:'Flexión de rodilla en bipedestación',ops:[0,1]},
{t:'Dorsiflexión de tobillo en bipedestación',ops:[0,1]},
{t:'Equilibrio en apoyo monopodal (pierna afectada)',ops:[0,1]},
]},
{n:'Brazo (15 ítems, 0=No puede, 1=Sí puede)',items:[
{t:'Elevación de escápula en supino',ops:[0,1]},
{t:'Elevación de brazo hacia adelante en supino',ops:[0,1]},
{t:'Extensión de codo con brazo elevado en supino',ops:[0,1]},
{t:'Control de pronosupinación en supino',ops:[0,1]},
{t:'Elevación de brazo en sedestación',ops:[0,1]},
{t:'Apoyo del brazo en extensión (protección)',ops:[0,1]},
{t:'Llevar la mano a la boca',ops:[0,1]},
{t:'Sujetar objeto y soltarlo',ops:[0,1]},
{t:'Prensión gruesa (agarrar un objeto grande)',ops:[0,1]},
{t:'Pinza fina (pulgar-índice)',ops:[0,1]},
{t:'Manipulación de objetos pequeños',ops:[0,1]},
{t:'Llevar objeto a la cabeza',ops:[0,1]},
{t:'Colocar la mano detrás de la espalda',ops:[0,1]},
{t:'Movimiento coordinado bimanual',ops:[0,1]},
{t:'Actividad funcional compleja con la mano (ej. abrochar botón)',ops:[0,1]},
]},
],
interp:(p)=>p>=30?{t:'Recuperación motora global avanzada.',bg:'#E8F5F0',c:'#1A7A5E'}:p>=15?{t:'Recuperación motora global en progreso.',bg:'#FFF3EB',c:'#C05621'}:{t:'Recuperación motora global inicial. Requiere intervención intensiva.',bg:'#FFF5F5',c:'#C53030'},
},
